<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="pt-BR" xml:lang="pt-BR"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Reinaldo Gomes">

<title>Relatório 3: Aprofundando a análise estatística do banco de dados utilizado no Relatório 2, explorando as principais medidas de posição e de dispersão aplicadas às variáveis quantitativas do estudo.</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="index_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap-efbb37e9afcc02144ebbc7afd12a776f.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Relatório 3: Aprofundando a análise estatística do banco de dados utilizado no Relatório 2, explorando as principais medidas de posição e de dispersão aplicadas às variáveis quantitativas do estudo.</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Autor</div>
    <div class="quarto-title-meta-contents">
             <p>Reinaldo Gomes </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Data de Publicação</div>
    <div class="quarto-title-meta-contents">
      <p class="date">15 de setembro de 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introdução" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Introdução</h1>
<section id="contextualização-do-estudo-no-cenário-educacional" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="contextualização-do-estudo-no-cenário-educacional"><span class="header-section-number">1.1</span> Contextualização do estudo no cenário educacional</h2>
</section>
<section id="objetivos-do-relatório" class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="objetivos-do-relatório"><span class="header-section-number">1.2</span> Objetivos do relatório</h2>
</section>
<section id="questões-norteadoras" class="level2" data-number="1.3">
<h2 data-number="1.3" class="anchored" data-anchor-id="questões-norteadoras"><span class="header-section-number">1.3</span> Questões norteadoras</h2>
<ul>
<li>Valor representativo do centro dos dados.</li>
<li>Homogeneidade versus heterogeneidade do comportamento dos alunos.</li>
<li>Adequação da média na presença de assimetria e valores extremos.</li>
<li>Comparação de grupos com médias semelhantes e comportamentos distintos.</li>
</ul>
</section>
</section>
<section id="descrição-do-banco-de-dados" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Descrição do banco de dados</h1>
<section id="origem-e-dimensão-dos-dados" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="origem-e-dimensão-dos-dados"><span class="header-section-number">2.1</span> Origem e dimensão dos dados</h2>
<p>Banco de dados constituído por 1.000 alunos de escola pública brasileira.</p>
</section>
<section id="variáveis-quantitativas-principais" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="variáveis-quantitativas-principais"><span class="header-section-number">2.2</span> Variáveis quantitativas principais</h2>
<ul>
<li>Faltas.</li>
<li>Nota Média.</li>
</ul>
</section>
<section id="variáveis-qualitativas-para-formação-de-subgrupos" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="variáveis-qualitativas-para-formação-de-subgrupos"><span class="header-section-number">2.3</span> Variáveis qualitativas para formação de subgrupos</h2>
<ul>
<li>Turno de estudo.</li>
<li>Escolaridade da mãe.</li>
<li>Acesso à internet em casa.</li>
</ul>
</section>
</section>
<section id="metodologia" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Metodologia</h1>
<section id="procedimento-de-importação-do-arquivo-dados_alunos.csv-no-r" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="procedimento-de-importação-do-arquivo-dados_alunos.csv-no-r"><span class="header-section-number">3.1</span> Procedimento de importação do arquivo dados_alunos.csv no R</h2>
</section>
<section id="medidas-de-posição" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="medidas-de-posição"><span class="header-section-number">3.2</span> Medidas de posição</h2>
<ul>
<li>Média.</li>
<li>Mediana.</li>
<li>Moda.</li>
<li>Quartis.</li>
<li>Percentis.</li>
</ul>
</section>
<section id="medidas-de-dispersão" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="medidas-de-dispersão"><span class="header-section-number">3.3</span> Medidas de dispersão</h2>
<ul>
<li>Amplitude.</li>
<li>Amplitude Interquartil (AIQ).</li>
<li>Variância.</li>
<li>Desvio-Padrão.</li>
<li>Coeficiente de Variação (CV).</li>
</ul>
</section>
<section id="ferramentas-e-pacotes-computacionais-empregados" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="ferramentas-e-pacotes-computacionais-empregados"><span class="header-section-number">3.4</span> Ferramentas e pacotes computacionais empregados</h2>
</section>
</section>
<section id="medidas-de-posição-1" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Medidas de posição</h1>
<section id="média-aritmética" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="média-aritmética"><span class="header-section-number">4.1</span> Média Aritmética</h2>
</section>
<section id="mediana" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="mediana"><span class="header-section-number">4.2</span> Mediana</h2>
</section>
<section id="moda" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="moda"><span class="header-section-number">4.3</span> Moda</h2>
</section>
<section id="quartis" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="quartis"><span class="header-section-number">4.4</span> Quartis</h2>
</section>
<section id="percentis" class="level2" data-number="4.5">
<h2 data-number="4.5" class="anchored" data-anchor-id="percentis"><span class="header-section-number">4.5</span> Percentis</h2>
</section>
</section>
<section id="medidas-de-dispersão-1" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Medidas de dispersão</h1>
<section id="amplitude-total" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="amplitude-total"><span class="header-section-number">5.1</span> Amplitude Total</h2>
</section>
<section id="amplitude-interquartil" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="amplitude-interquartil"><span class="header-section-number">5.2</span> Amplitude Interquartil</h2>
</section>
<section id="variância-amostral" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="variância-amostral"><span class="header-section-number">5.3</span> Variância Amostral</h2>
</section>
<section id="desvio-padrão-amostral" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="desvio-padrão-amostral"><span class="header-section-number">5.4</span> Desvio-Padrão Amostral</h2>
</section>
<section id="coeficiente-de-variação" class="level2" data-number="5.5">
<h2 data-number="5.5" class="anchored" data-anchor-id="coeficiente-de-variação"><span class="header-section-number">5.5</span> Coeficiente de Variação</h2>
</section>
</section>
<section id="análise-por-subgrupos" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Análise por subgrupos</h1>
<section id="notas-segundo-o-acesso-à-internet" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="notas-segundo-o-acesso-à-internet"><span class="header-section-number">6.1</span> Notas segundo o Acesso à Internet</h2>
<section id="comparação-entre-alunos-com-e-sem-acesso-à-internet" class="level3" data-number="6.1.1">
<h3 data-number="6.1.1" class="anchored" data-anchor-id="comparação-entre-alunos-com-e-sem-acesso-à-internet"><span class="header-section-number">6.1.1</span> Comparação entre alunos com e sem acesso à internet</h3>
</section>
</section>
<section id="notas-segundo-a-escolaridade-da-mãe" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="notas-segundo-a-escolaridade-da-mãe"><span class="header-section-number">6.2</span> Notas segundo a Escolaridade da Mãe</h2>
<section id="comparação-entre-fundamental-médio-e-superior" class="level3" data-number="6.2.1">
<h3 data-number="6.2.1" class="anchored" data-anchor-id="comparação-entre-fundamental-médio-e-superior"><span class="header-section-number">6.2.1</span> Comparação entre Fundamental, Médio e Superior</h3>
</section>
</section>
<section id="faltas-segundo-o-turno-de-estudo" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="faltas-segundo-o-turno-de-estudo"><span class="header-section-number">6.3</span> Faltas segundo o Turno de Estudo</h2>
<section id="comparação-entre-matutino-vespertino-e-noturno" class="level3" data-number="6.3.1">
<h3 data-number="6.3.1" class="anchored" data-anchor-id="comparação-entre-matutino-vespertino-e-noturno"><span class="header-section-number">6.3.1</span> Comparação entre Matutino, Vespertino e Noturno</h3>
</section>
</section>
</section>
<section id="representações-gráficas" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Representações gráficas</h1>
<section id="boxplots-globais" class="level2" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="boxplots-globais"><span class="header-section-number">7.1</span> Boxplots Globais</h2>
<section id="boxplot-da-nota-média" class="level3" data-number="7.1.1">
<h3 data-number="7.1.1" class="anchored" data-anchor-id="boxplot-da-nota-média"><span class="header-section-number">7.1.1</span> Boxplot da Nota Média</h3>
</section>
<section id="boxplot-das-faltas" class="level3" data-number="7.1.2">
<h3 data-number="7.1.2" class="anchored" data-anchor-id="boxplot-das-faltas"><span class="header-section-number">7.1.2</span> Boxplot das Faltas</h3>
</section>
</section>
<section id="gráficos-comparativos-por-subgrupos" class="level2" data-number="7.2">
<h2 data-number="7.2" class="anchored" data-anchor-id="gráficos-comparativos-por-subgrupos"><span class="header-section-number">7.2</span> Gráficos Comparativos por Subgrupos</h2>
<section id="distribuição-das-notas-por-acesso-à-internet" class="level3" data-number="7.2.1">
<h3 data-number="7.2.1" class="anchored" data-anchor-id="distribuição-das-notas-por-acesso-à-internet"><span class="header-section-number">7.2.1</span> Distribuição das Notas por Acesso à Internet</h3>
</section>
<section id="distribuição-das-notas-por-escolaridade-da-mãe" class="level3" data-number="7.2.2">
<h3 data-number="7.2.2" class="anchored" data-anchor-id="distribuição-das-notas-por-escolaridade-da-mãe"><span class="header-section-number">7.2.2</span> Distribuição das Notas por Escolaridade da Mãe</h3>
</section>
<section id="distribuição-das-faltas-por-turno-de-estudo" class="level3" data-number="7.2.3">
<h3 data-number="7.2.3" class="anchored" data-anchor-id="distribuição-das-faltas-por-turno-de-estudo"><span class="header-section-number">7.2.3</span> Distribuição das Faltas por Turno de Estudo</h3>
</section>
</section>
<section id="integração-e-interpretação-estatística-dos-gráficos" class="level2" data-number="7.3">
<h2 data-number="7.3" class="anchored" data-anchor-id="integração-e-interpretação-estatística-dos-gráficos"><span class="header-section-number">7.3</span> Integração e interpretação estatística dos gráficos</h2>
</section>
</section>
<section id="discussão-dos-resultados" class="level1" data-number="8">
<h1 data-number="8"><span class="header-section-number">8</span> Discussão dos resultados</h1>
<section id="média-versus-mediana" class="level2" data-number="8.1">
<h2 data-number="8.1" class="anchored" data-anchor-id="média-versus-mediana"><span class="header-section-number">8.1</span> Média versus Mediana</h2>
</section>
<section id="o-efeito-da-variabilidade" class="level2" data-number="8.2">
<h2 data-number="8.2" class="anchored" data-anchor-id="o-efeito-da-variabilidade"><span class="header-section-number">8.2</span> O efeito da variabilidade</h2>
</section>
<section id="seleção-das-medidas-estatísticas-mais-adequadas" class="level2" data-number="8.3">
<h2 data-number="8.3" class="anchored" data-anchor-id="seleção-das-medidas-estatísticas-mais-adequadas"><span class="header-section-number">8.3</span> Seleção das medidas estatísticas mais adequadas</h2>
<section id="desempenho-médio-global" class="level3" data-number="8.3.1">
<h3 data-number="8.3.1" class="anchored" data-anchor-id="desempenho-médio-global"><span class="header-section-number">8.3.1</span> Desempenho médio global</h3>
</section>
<section id="desempenho-típico-com-valores-extremos" class="level3" data-number="8.3.2">
<h3 data-number="8.3.2" class="anchored" data-anchor-id="desempenho-típico-com-valores-extremos"><span class="header-section-number">8.3.2</span> Desempenho típico com valores extremos</h3>
</section>
<section id="dispersão-das-notas" class="level3" data-number="8.3.3">
<h3 data-number="8.3.3" class="anchored" data-anchor-id="dispersão-das-notas"><span class="header-section-number">8.3.3</span> Dispersão das notas</h3>
</section>
<section id="comparação-da-variabilidade" class="level3" data-number="8.3.4">
<h3 data-number="8.3.4" class="anchored" data-anchor-id="comparação-da-variabilidade"><span class="header-section-number">8.3.4</span> Comparação da variabilidade</h3>
</section>
<section id="posição-relativa-de-um-aluno-no-grupo" class="level3" data-number="8.3.5">
<h3 data-number="8.3.5" class="anchored" data-anchor-id="posição-relativa-de-um-aluno-no-grupo"><span class="header-section-number">8.3.5</span> Posição relativa de um aluno no grupo</h3>
</section>
</section>
<section id="tabela-síntese-comparativa" class="level2" data-number="8.4">
<h2 data-number="8.4" class="anchored" data-anchor-id="tabela-síntese-comparativa"><span class="header-section-number">8.4</span> Tabela-síntese comparativa</h2>
<section id="mínimo" class="level3" data-number="8.4.1">
<h3 data-number="8.4.1" class="anchored" data-anchor-id="mínimo"><span class="header-section-number">8.4.1</span> Mínimo</h3>
</section>
<section id="q1" class="level3" data-number="8.4.2">
<h3 data-number="8.4.2" class="anchored" data-anchor-id="q1"><span class="header-section-number">8.4.2</span> Q1</h3>
</section>
<section id="média" class="level3" data-number="8.4.3">
<h3 data-number="8.4.3" class="anchored" data-anchor-id="média"><span class="header-section-number">8.4.3</span> Média</h3>
</section>
<section id="mediana-1" class="level3" data-number="8.4.4">
<h3 data-number="8.4.4" class="anchored" data-anchor-id="mediana-1"><span class="header-section-number">8.4.4</span> Mediana</h3>
</section>
<section id="q3" class="level3" data-number="8.4.5">
<h3 data-number="8.4.5" class="anchored" data-anchor-id="q3"><span class="header-section-number">8.4.5</span> Q3</h3>
</section>
<section id="máximo" class="level3" data-number="8.4.6">
<h3 data-number="8.4.6" class="anchored" data-anchor-id="máximo"><span class="header-section-number">8.4.6</span> Máximo</h3>
</section>
<section id="amplitude" class="level3" data-number="8.4.7">
<h3 data-number="8.4.7" class="anchored" data-anchor-id="amplitude"><span class="header-section-number">8.4.7</span> Amplitude</h3>
</section>
<section id="aiq" class="level3" data-number="8.4.8">
<h3 data-number="8.4.8" class="anchored" data-anchor-id="aiq"><span class="header-section-number">8.4.8</span> AIQ</h3>
</section>
<section id="variância" class="level3" data-number="8.4.9">
<h3 data-number="8.4.9" class="anchored" data-anchor-id="variância"><span class="header-section-number">8.4.9</span> Variância</h3>
</section>
<section id="desvio-padrão" class="level3" data-number="8.4.10">
<h3 data-number="8.4.10" class="anchored" data-anchor-id="desvio-padrão"><span class="header-section-number">8.4.10</span> Desvio-Padrão</h3>
</section>
<section id="coeficiente-de-variação-1" class="level3" data-number="8.4.11">
<h3 data-number="8.4.11" class="anchored" data-anchor-id="coeficiente-de-variação-1"><span class="header-section-number">8.4.11</span> Coeficiente de Variação</h3>
</section>
</section>
</section>
<section id="conclusões" class="level1" data-number="9">
<h1 data-number="9"><span class="header-section-number">9</span> Conclusões</h1>
<section id="síntese-dos-achados-sobre-as-variáveis-faltas-e-nota-média" class="level2" data-number="9.1">
<h2 data-number="9.1" class="anchored" data-anchor-id="síntese-dos-achados-sobre-as-variáveis-faltas-e-nota-média"><span class="header-section-number">9.1</span> Síntese dos achados sobre as variáveis Faltas e Nota Média</h2>
</section>
<section id="identificação-da-variável-de-maior-variabilidade-relativa" class="level2" data-number="9.2">
<h2 data-number="9.2" class="anchored" data-anchor-id="identificação-da-variável-de-maior-variabilidade-relativa"><span class="header-section-number">9.2</span> Identificação da variável de maior variabilidade relativa</h2>
</section>
<section id="resumo-das-diferenças-observadas-entre-os-subgrupos-analisados" class="level2" data-number="9.3">
<h2 data-number="9.3" class="anchored" data-anchor-id="resumo-das-diferenças-observadas-entre-os-subgrupos-analisados"><span class="header-section-number">9.3</span> Resumo das diferenças observadas entre os subgrupos analisados</h2>
</section>
</section>
<section id="limitações-da-análise" class="level1" data-number="10">
<h1 data-number="10"><span class="header-section-number">10</span> Limitações da análise</h1>
<section id="cuidados-e-precauções-na-interpretação-das-diferenças-entre-grupos" class="level2" data-number="10.1">
<h2 data-number="10.1" class="anchored" data-anchor-id="cuidados-e-precauções-na-interpretação-das-diferenças-entre-grupos"><span class="header-section-number">10.1</span> Cuidados e precauções na interpretação das diferenças entre grupos</h2>
</section>
<section id="distinção-entre-descrição-estatística-associação-e-causalidade" class="level2" data-number="10.2">
<h2 data-number="10.2" class="anchored" data-anchor-id="distinção-entre-descrição-estatística-associação-e-causalidade"><span class="header-section-number">10.2</span> Distinção entre descrição estatística, associação e causalidade</h2>
</section>
<section id="impossibilidade-de-inferir-relações-de-causa-e-efeito-sem-controle-de-variáveis" class="level2" data-number="10.3">
<h2 data-number="10.3" class="anchored" data-anchor-id="impossibilidade-de-inferir-relações-de-causa-e-efeito-sem-controle-de-variáveis"><span class="header-section-number">10.3</span> Impossibilidade de inferir relações de causa e efeito sem controle de variáveis</h2>
</section>
</section>
<section id="código-r-utilizado" class="level1" data-number="11">
<h1 data-number="11"><span class="header-section-number">11</span> Código R utilizado</h1>
<section id="importação-e-preparação-dos-dados" class="level2" data-number="11.1">
<h2 data-number="11.1" class="anchored" data-anchor-id="importação-e-preparação-dos-dados"><span class="header-section-number">11.1</span> Importação e preparação dos dados</h2>
</section>
<section id="cálculo-das-medidas-estatísticas" class="level2" data-number="11.2">
<h2 data-number="11.2" class="anchored" data-anchor-id="cálculo-das-medidas-estatísticas"><span class="header-section-number">11.2</span> Cálculo das medidas estatísticas</h2>
</section>
<section id="análise-dos-subgrupos" class="level2" data-number="11.3">
<h2 data-number="11.3" class="anchored" data-anchor-id="análise-dos-subgrupos"><span class="header-section-number">11.3</span> Análise dos subgrupos</h2>
</section>
<section id="construção-dos-gráficos" class="level2" data-number="11.4">
<h2 data-number="11.4" class="anchored" data-anchor-id="construção-dos-gráficos"><span class="header-section-number">11.4</span> Construção dos gráficos</h2>
</section>
<section id="referências-bibliográficas" class="level2" data-number="11.5">
<h2 data-number="11.5" class="anchored" data-anchor-id="referências-bibliográficas"><span class="header-section-number">11.5</span> # Referências bibliográficas</h2>
<p>title: “Relatório 3: Aprofundando a análise estatística do banco de dados utilizado no Relatório 2, explorando as principais medidas de posição e de dispersão aplicadas às variáveis quantitativas do estudo” author: “Reinaldo Gomes” date: “15/09/2026” format: html: toc: true toc-depth: 3 number-sections: true lang: pt-BR execute: echo: false warning: false message: false ————–</p>
</section>
</section>
<section id="introdução-1" class="level1" data-number="12">
<h1 data-number="12"><span class="header-section-number">12</span> 1 Introdução</h1>
<section id="contextualização-do-estudo-no-cenário-educacional-1" class="level2" data-number="12.1">
<h2 data-number="12.1" class="anchored" data-anchor-id="contextualização-do-estudo-no-cenário-educacional-1"><span class="header-section-number">12.1</span> 1.1 Contextualização do estudo no cenário educacional</h2>
<p>A análise estatística de dados educacionais permite compreender diferentes aspectos relacionados ao desempenho e à frequência dos alunos. Entretanto, a simples apresentação de uma média não é suficiente para representar completamente um conjunto de dados.</p>
<p>Dois grupos podem apresentar médias semelhantes e, ainda assim, possuir comportamentos bastante diferentes. Um grupo pode apresentar resultados concentrados próximos da média, enquanto outro pode apresentar grande dispersão, com alunos situados em posições muito distintas.</p>
<p>Neste relatório, são analisadas duas variáveis quantitativas do banco de dados: o número de <strong>faltas</strong> e a <strong>nota média</strong> dos alunos. Além da análise global, são realizadas comparações entre grupos definidos pelo acesso à internet, pela escolaridade da mãe e pelo turno de estudo.</p>
<p>A análise busca relacionar os resultados numéricos ao contexto educacional, utilizando medidas de posição, medidas de dispersão e representações gráficas.</p>
</section>
<section id="objetivos-do-relatório-1" class="level2" data-number="12.2">
<h2 data-number="12.2" class="anchored" data-anchor-id="objetivos-do-relatório-1"><span class="header-section-number">12.2</span> 1.2 Objetivos do relatório</h2>
<p>O objetivo deste relatório é aprofundar a análise estatística do banco de dados utilizado anteriormente, explorando medidas de posição e de dispersão aplicadas às variáveis quantitativas.</p>
<p>Especificamente, pretende-se:</p>
<ul>
<li>calcular e interpretar média, mediana e moda;</li>
<li>determinar quartis e percentis;</li>
<li>calcular amplitude, amplitude interquartil, variância, desvio-padrão e coeficiente de variação;</li>
<li>comparar o comportamento das notas e das faltas;</li>
<li>analisar diferenças entre subgrupos de alunos;</li>
<li>utilizar gráficos para complementar a análise numérica;</li>
<li>discutir as diferenças entre média e mediana;</li>
<li>identificar limitações das conclusões baseadas apenas em estatísticas descritivas.</li>
</ul>
</section>
<section id="questões-norteadoras-1" class="level2" data-number="12.3">
<h2 data-number="12.3" class="anchored" data-anchor-id="questões-norteadoras-1"><span class="header-section-number">12.3</span> 1.3 Questões norteadoras</h2>
<p>A análise foi desenvolvida buscando responder às seguintes questões:</p>
<ul>
<li>Qual valor representa melhor o centro dos dados?</li>
<li>Os alunos apresentam comportamento homogêneo ou heterogêneo?</li>
<li>A média é adequada quando existem assimetrias ou valores extremos?</li>
<li>Dois grupos podem apresentar médias semelhantes e comportamentos diferentes?</li>
</ul>
<p>Essas questões orientam a interpretação dos resultados apresentados ao longo do relatório.</p>
</section>
</section>
<section id="descrição-do-banco-de-dados-1" class="level1" data-number="13">
<h1 data-number="13"><span class="header-section-number">13</span> 2 Descrição do banco de dados</h1>
<section id="origem-e-dimensão-dos-dados-1" class="level2" data-number="13.1">
<h2 data-number="13.1" class="anchored" data-anchor-id="origem-e-dimensão-dos-dados-1"><span class="header-section-number">13.1</span> 2.1 Origem e dimensão dos dados</h2>
<p>O banco de dados é constituído por informações referentes a <strong>1000 alunos</strong> de uma escola pública brasileira.</p>
<p>Cada linha representa um aluno, enquanto as colunas apresentam informações quantitativas e qualitativas utilizadas na análise estatística.</p>
<p>O banco contém <strong>5 variáveis</strong>, permitindo tanto uma análise global quanto a comparação entre diferentes subgrupos.</p>
</section>
<section id="variáveis-quantitativas-principais-1" class="level2" data-number="13.2">
<h2 data-number="13.2" class="anchored" data-anchor-id="variáveis-quantitativas-principais-1"><span class="header-section-number">13.2</span> 2.2 Variáveis quantitativas principais</h2>
<p>As duas principais variáveis quantitativas analisadas são:</p>
<ul>
<li><strong>Faltas:</strong> representa o número de faltas registradas por aluno.</li>
<li><strong>Nota Média:</strong> representa o desempenho médio do aluno em uma escala de 0 a 10.</li>
</ul>
<p>A variável faltas apresentou valores entre <strong>1</strong> e <strong>19</strong>.</p>
<p>A variável nota média apresentou valores entre <strong>0.5</strong> e <strong>10</strong>.</p>
</section>
<section id="variáveis-qualitativas-para-formação-de-subgrupos-1" class="level2" data-number="13.3">
<h2 data-number="13.3" class="anchored" data-anchor-id="variáveis-qualitativas-para-formação-de-subgrupos-1"><span class="header-section-number">13.3</span> 2.3 Variáveis qualitativas para formação de subgrupos</h2>
<p>As variáveis qualitativas utilizadas para a formação dos grupos são:</p>
<ul>
<li><strong>Turno de estudo:</strong> Matutino, Vespertino e Noturno;</li>
<li><strong>Escolaridade da mãe:</strong> Fundamental, Médio e Superior;</li>
<li><strong>Acesso à internet em casa:</strong> Sim ou Não.</li>
</ul>
<p>Essas variáveis permitem comparar medidas de posição e dispersão entre diferentes grupos de alunos.</p>
</section>
</section>
<section id="metodologia-1" class="level1" data-number="14">
<h1 data-number="14"><span class="header-section-number">14</span> 3 Metodologia</h1>
<section id="procedimento-de-importação-do-arquivo-dados_alunos.csv-no-r-1" class="level2" data-number="14.1">
<h2 data-number="14.1" class="anchored" data-anchor-id="procedimento-de-importação-do-arquivo-dados_alunos.csv-no-r-1"><span class="header-section-number">14.1</span> 3.1 Procedimento de importação do arquivo dados_alunos.csv no R</h2>
<p>O banco de dados foi importado para o R utilizando a função <code>read.table()</code>, considerando o ponto e vírgula como separador entre os campos.</p>
<p>Após a importação, foi realizada uma preparação da variável <code>nota_media</code>, garantindo sua conversão para formato numérico.</p>
<p>O procedimento utilizado foi:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>dados_alunos <span class="ot">&lt;-</span> <span class="fu">read.table</span>(</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">file =</span> <span class="st">"dados_alunos.csv"</span>,</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">header =</span> <span class="cn">TRUE</span>,</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">sep =</span> <span class="st">";"</span>,</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">dec =</span> <span class="st">","</span>,</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">stringsAsFactors =</span> <span class="cn">FALSE</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>dados_alunos<span class="sc">$</span>nota_media <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gsub</span>(<span class="st">","</span>, <span class="st">"."</span>, <span class="fu">as.character</span>(dados_alunos<span class="sc">$</span>nota_media))</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="medidas-de-posição-2" class="level2" data-number="14.2">
<h2 data-number="14.2" class="anchored" data-anchor-id="medidas-de-posição-2"><span class="header-section-number">14.2</span> 3.2 Medidas de posição</h2>
<p>Foram utilizadas as seguintes medidas de posição:</p>
<ul>
<li>média;</li>
<li>mediana;</li>
<li>moda;</li>
<li>quartis;</li>
<li>percentis.</li>
</ul>
<p>Essas medidas permitem identificar valores centrais e posições relativas dentro da distribuição.</p>
</section>
<section id="medidas-de-dispersão-2" class="level2" data-number="14.3">
<h2 data-number="14.3" class="anchored" data-anchor-id="medidas-de-dispersão-2"><span class="header-section-number">14.3</span> 3.3 Medidas de dispersão</h2>
<p>Também foram calculadas as seguintes medidas:</p>
<ul>
<li>amplitude;</li>
<li>amplitude interquartil;</li>
<li>variância;</li>
<li>desvio-padrão;</li>
<li>coeficiente de variação.</li>
</ul>
<p>Essas medidas permitem verificar o grau de concentração ou dispersão dos valores.</p>
</section>
<section id="ferramentas-e-pacotes-computacionais-empregados-1" class="level2" data-number="14.4">
<h2 data-number="14.4" class="anchored" data-anchor-id="ferramentas-e-pacotes-computacionais-empregados-1"><span class="header-section-number">14.4</span> 3.4 Ferramentas e pacotes computacionais empregados</h2>
<p>A análise foi realizada utilizando o software <strong>R</strong> e o ambiente <strong>RStudio</strong>.</p>
<p>Foram utilizadas principalmente funções da instalação básica do R, como:</p>
<ul>
<li><code>mean()</code>;</li>
<li><code>median()</code>;</li>
<li><code>quantile()</code>;</li>
<li><code>var()</code>;</li>
<li><code>sd()</code>;</li>
<li><code>IQR()</code>;</li>
<li><code>aggregate()</code>;</li>
<li><code>boxplot()</code>.</li>
</ul>
<p>A utilização de funções básicas torna o código mais simples e reduz a necessidade de instalação de pacotes adicionais.</p>
</section>
</section>
<section id="medidas-de-posição-3" class="level1" data-number="15">
<h1 data-number="15"><span class="header-section-number">15</span> 4 Medidas de posição</h1>
<section id="média-aritmética-1" class="level2" data-number="15.1">
<h2 data-number="15.1" class="anchored" data-anchor-id="média-aritmética-1"><span class="header-section-number">15.1</span> 4.1 Média Aritmética</h2>
<p>A média aritmética do número de faltas foi de <strong>8.01 faltas</strong>.</p>
<p>Isso significa que, considerando todos os alunos, o número médio de faltas ficou próximo de 8 faltas por aluno.</p>
<p>A média da variável Nota Média foi de <strong>6.44 pontos</strong>.</p>
<p>Portanto, o desempenho médio global dos alunos ficou em aproximadamente 6,44 pontos.</p>
<p>Embora a média seja uma medida importante, sua interpretação deve ser complementada pela mediana e pelas medidas de dispersão, pois a média pode ser influenciada por valores extremos.</p>
</section>
<section id="mediana-2" class="level2" data-number="15.2">
<h2 data-number="15.2" class="anchored" data-anchor-id="mediana-2"><span class="header-section-number">15.2</span> 4.2 Mediana</h2>
<p>A mediana do número de faltas foi de <strong>8</strong>.</p>
<p>Isso significa que aproximadamente metade dos alunos apresentou até 8 faltas, enquanto a outra metade apresentou 8 faltas ou mais.</p>
<p>A mediana da Nota Média foi de <strong>6.5 pontos</strong>.</p>
<p>A comparação mostra que:</p>
<ul>
<li>para faltas, a média foi 8.01 e a mediana foi 8;</li>
<li>para notas, a média foi 6.44 e a mediana foi 6.5.</li>
</ul>
<p>Em ambos os casos, média e mediana apresentam valores relativamente próximos. Isso indica que, globalmente, não existe uma diferença muito acentuada entre o valor médio e o valor central da distribuição.</p>
<p>No entanto, essa proximidade não elimina a necessidade de analisar a dispersão e os possíveis valores extremos.</p>
</section>
<section id="moda-1" class="level2" data-number="15.3">
<h2 data-number="15.3" class="anchored" data-anchor-id="moda-1"><span class="header-section-number">15.3</span> 4.3 Moda</h2>
<p>A moda do número de faltas foi <strong>7</strong>, sendo o valor com maior frequência no conjunto de dados.</p>
<p>Para a Nota Média, a moda foi <strong>10</strong>.</p>
<p>A moda representa o valor mais frequente observado. Ela é particularmente útil para identificar o resultado que mais se repete entre os alunos, embora não represente necessariamente o centro da distribuição.</p>
</section>
<section id="quartis-1" class="level2" data-number="15.4">
<h2 data-number="15.4" class="anchored" data-anchor-id="quartis-1"><span class="header-section-number">15.4</span> 4.4 Quartis</h2>
<p>Os quartis da variável Faltas foram:</p>
<ul>
<li>Primeiro quartil (Q1): <strong>6</strong>;</li>
<li>Segundo quartil (Q2 ou mediana): <strong>8</strong>;</li>
<li>Terceiro quartil (Q3): <strong>10</strong>.</li>
</ul>
<p>Isso significa que aproximadamente 25% dos alunos apresentaram até 6 faltas. Metade apresentou até 8 faltas, e aproximadamente 75% apresentaram até 10 faltas.</p>
<p>Para a Nota Média, os quartis foram:</p>
<ul>
<li>Primeiro quartil (Q1): <strong>5.2</strong>;</li>
<li>Segundo quartil (Q2): <strong>6.5</strong>;</li>
<li>Terceiro quartil (Q3): <strong>7.7</strong>.</li>
</ul>
<p>Assim, aproximadamente 25% dos alunos apresentaram nota até 5.2, enquanto 75% apresentaram nota até 7.7.</p>
<p>O intervalo entre Q1 e Q3 representa a região central onde se encontra metade dos alunos.</p>
</section>
<section id="percentis-1" class="level2" data-number="15.5">
<h2 data-number="15.5" class="anchored" data-anchor-id="percentis-1"><span class="header-section-number">15.5</span> 4.5 Percentis</h2>
<p>Foram calculados os percentis 10, 25, 50, 75 e 90.</p>
<section id="percentis-das-faltas" class="level3" data-number="15.5.1">
<h3 data-number="15.5.1" class="anchored" data-anchor-id="percentis-das-faltas"><span class="header-section-number">15.5.1</span> Percentis das faltas</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">Percentil =</span> <span class="fu">c</span>(<span class="st">"P10"</span>, <span class="st">"P25"</span>, <span class="st">"P50"</span>, <span class="st">"P75"</span>, <span class="st">"P90"</span>),</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">Valor =</span> <span class="fu">as.numeric</span>(percentis_faltas)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Percentil Valor
1       P10     5
2       P25     6
3       P50     8
4       P75    10
5       P90    12</code></pre>
</div>
</div>
<p>O percentil 10 indica um valor abaixo do qual se encontram aproximadamente 10% dos alunos. O percentil 50 corresponde à mediana, enquanto o percentil 90 indica um valor abaixo do qual se encontram aproximadamente 90% dos alunos.</p>
</section>
<section id="percentis-da-nota-média" class="level3" data-number="15.5.2">
<h3 data-number="15.5.2" class="anchored" data-anchor-id="percentis-da-nota-média"><span class="header-section-number">15.5.2</span> Percentis da Nota Média</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">Percentil =</span> <span class="fu">c</span>(<span class="st">"P10"</span>, <span class="st">"P25"</span>, <span class="st">"P50"</span>, <span class="st">"P75"</span>, <span class="st">"P90"</span>),</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">Valor =</span> <span class="fu">round</span>(<span class="fu">as.numeric</span>(percentis_notas), <span class="dv">2</span>)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Percentil Valor
1       P10  3.99
2       P25  5.20
3       P50  6.50
4       P75  7.70
5       P90  9.10</code></pre>
</div>
</div>
<p>Para as notas, o percentil 90 foi de aproximadamente <strong>9.1</strong>. Isso indica que cerca de 90% dos alunos apresentaram notas até esse valor, enquanto aproximadamente 10% ficaram acima dele.</p>
<p>Os percentis são úteis porque permitem localizar a posição relativa de um aluno dentro do conjunto analisado.</p>
</section>
</section>
</section>
<section id="medidas-de-dispersão-3" class="level1" data-number="16">
<h1 data-number="16"><span class="header-section-number">16</span> 5 Medidas de dispersão</h1>
<section id="amplitude-total-1" class="level2" data-number="16.1">
<h2 data-number="16.1" class="anchored" data-anchor-id="amplitude-total-1"><span class="header-section-number">16.1</span> 5.1 Amplitude Total</h2>
<p>A amplitude total é obtida pela diferença entre o maior e o menor valor.</p>
<p>Para Faltas:</p>
<p><strong>Amplitude = 18</strong></p>
<p>Isso mostra que os valores de faltas se distribuem em um intervalo de 18 unidades.</p>
<p>Para Nota Média:</p>
<p><strong>Amplitude = 9.5</strong></p>
<p>A nota média apresentou uma variação total de 9,5 pontos entre o menor e o maior valor.</p>
<p>A amplitude fornece uma visão geral da extensão dos dados, mas pode ser fortemente influenciada por valores extremos.</p>
</section>
<section id="amplitude-interquartil-1" class="level2" data-number="16.2">
<h2 data-number="16.2" class="anchored" data-anchor-id="amplitude-interquartil-1"><span class="header-section-number">16.2</span> 5.2 Amplitude Interquartil</h2>
<p>A amplitude interquartil, também chamada de AIQ, representa a diferença entre o terceiro e o primeiro quartil.</p>
<p>Para Faltas:</p>
<p><strong>AIQ = 4</strong></p>
<p>Para Nota Média:</p>
<p><strong>AIQ = 2.5</strong></p>
<p>A AIQ representa a dispersão dos 50% centrais dos dados. Como não depende diretamente dos valores mínimo e máximo, ela é menos influenciada por possíveis valores extremos.</p>
</section>
<section id="variância-amostral-1" class="level2" data-number="16.3">
<h2 data-number="16.3" class="anchored" data-anchor-id="variância-amostral-1"><span class="header-section-number">16.3</span> 5.3 Variância Amostral</h2>
<p>A variância amostral das Faltas foi de aproximadamente:</p>
<p><strong>7.83</strong></p>
<p>A variância da Nota Média foi de aproximadamente:</p>
<p><strong>3.54</strong></p>
<p>A variância representa uma medida de dispersão baseada nos desvios dos valores em relação à média.</p>
<p>Sua interpretação direta pode ser menos intuitiva porque sua unidade está elevada ao quadrado. Por exemplo, a variância das faltas é expressa em faltas ao quadrado.</p>
<p>Por esse motivo, o desvio-padrão costuma ser mais facilmente interpretado.</p>
</section>
<section id="desvio-padrão-amostral-1" class="level2" data-number="16.4">
<h2 data-number="16.4" class="anchored" data-anchor-id="desvio-padrão-amostral-1"><span class="header-section-number">16.4</span> 5.4 Desvio-Padrão Amostral</h2>
<p>O desvio-padrão das Faltas foi de aproximadamente <strong>2.8</strong>.</p>
<p>Isso indica o grau médio de afastamento dos números de faltas em relação à média de aproximadamente 8,01 faltas.</p>
<p>Para a Nota Média, o desvio-padrão foi de aproximadamente <strong>1.88 pontos</strong>.</p>
<p>A comparação direta dos desvios-padrão deve ser feita com cuidado porque as duas variáveis possuem escalas e unidades diferentes.</p>
</section>
<section id="coeficiente-de-variação-2" class="level2" data-number="16.5">
<h2 data-number="16.5" class="anchored" data-anchor-id="coeficiente-de-variação-2"><span class="header-section-number">16.5</span> 5.5 Coeficiente de Variação</h2>
<p>O coeficiente de variação das Faltas foi de:</p>
<p><strong>34.93%</strong></p>
<p>O coeficiente de variação da Nota Média foi de:</p>
<p><strong>29.21%</strong></p>
<p>Comparando os dois resultados, observa-se que a variável <strong>Faltas apresenta maior variabilidade relativa</strong>.</p>
<p>Isso significa que, proporcionalmente à sua média, os valores de faltas apresentam maior dispersão do que as notas.</p>
<p>O coeficiente de variação é especialmente útil nessa comparação porque transforma a dispersão em uma medida relativa à média de cada variável.</p>
</section>
</section>
<section id="análise-por-subgrupos-1" class="level1" data-number="17">
<h1 data-number="17"><span class="header-section-number">17</span> 6 Análise por subgrupos</h1>
<section id="notas-segundo-o-acesso-à-internet-1" class="level2" data-number="17.1">
<h2 data-number="17.1" class="anchored" data-anchor-id="notas-segundo-o-acesso-à-internet-1"><span class="header-section-number">17.1</span> 6.1 Notas segundo o Acesso à Internet</h2>
<p>A análise a seguir compara as notas dos alunos que possuem e dos que não possuem acesso à internet em casa.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>internet_arredondado <span class="ot">&lt;-</span> internet</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>internet_arredondado[, <span class="sc">-</span><span class="dv">1</span>] <span class="ot">&lt;-</span> <span class="fu">round</span>(</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  internet_arredondado[, <span class="sc">-</span><span class="dv">1</span>],</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>  <span class="dv">2</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>internet_arredondado</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  acesso_internet Média Mediana Desvio.Padrão Mínimo Máximo Amplitude AIQ
1             Não  6.48     6.5          1.90    1.1     10       8.9 2.6
2             Sim  6.43     6.5          1.87    0.5     10       9.5 2.5</code></pre>
</div>
</div>
<section id="comparação-entre-alunos-com-e-sem-acesso-à-internet-1" class="level3" data-number="17.1.1">
<h3 data-number="17.1.1" class="anchored" data-anchor-id="comparação-entre-alunos-com-e-sem-acesso-à-internet-1"><span class="header-section-number">17.1.1</span> 6.1.1 Comparação entre alunos com e sem acesso à internet</h3>
<p>Os alunos sem acesso à internet apresentaram média de aproximadamente <strong>6.48</strong>, enquanto os alunos com acesso apresentaram média de aproximadamente <strong>6.43</strong>.</p>
<p>As medianas dos dois grupos foram próximas, o que sugere que o desempenho central dos grupos é semelhante.</p>
<p>Além disso, os desvios-padrão também apresentaram valores próximos, indicando níveis semelhantes de dispersão.</p>
<p>Portanto, neste banco de dados, a comparação descritiva não revela uma diferença expressiva entre os grupos em relação ao desempenho médio das notas.</p>
<p>Entretanto, essa observação descreve apenas os dados analisados e não permite concluir que o acesso à internet seja, isoladamente, responsável pelo desempenho escolar.</p>
</section>
</section>
<section id="notas-segundo-a-escolaridade-da-mãe-1" class="level2" data-number="17.2">
<h2 data-number="17.2" class="anchored" data-anchor-id="notas-segundo-a-escolaridade-da-mãe-1"><span class="header-section-number">17.2</span> 6.2 Notas segundo a Escolaridade da Mãe</h2>
<p>A seguir são apresentadas as principais medidas das notas segundo a escolaridade da mãe.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>escolaridade_arredondada <span class="ot">&lt;-</span> escolaridade</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>escolaridade_arredondada[, <span class="sc">-</span><span class="dv">1</span>] <span class="ot">&lt;-</span> <span class="fu">round</span>(</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  escolaridade_arredondada[, <span class="sc">-</span><span class="dv">1</span>],</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  <span class="dv">2</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>escolaridade_arredondada</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  escolaridade_mae Média Mediana Desvio.Padrão Mínimo Máximo Amplitude AIQ
1      Fundamental  6.33     6.5          1.85    1.0     10       9.0 2.6
2            Médio  6.55     6.5          1.85    0.5     10       9.5 2.4
3         Superior  6.41     6.2          2.05    1.7     10       8.3 3.0</code></pre>
</div>
</div>
<section id="comparação-entre-fundamental-médio-e-superior-1" class="level3" data-number="17.2.1">
<h3 data-number="17.2.1" class="anchored" data-anchor-id="comparação-entre-fundamental-médio-e-superior-1"><span class="header-section-number">17.2.1</span> 6.2.1 Comparação entre Fundamental, Médio e Superior</h3>
<p>Os grupos apresentaram médias aproximadas de:</p>
<ul>
<li>Fundamental: <strong>6.33</strong>;</li>
<li>Médio: <strong>6.55</strong>;</li>
<li>Superior: <strong>6.41</strong>.</li>
</ul>
<p>As médias não apresentam um crescimento perfeitamente contínuo conforme aumenta a escolaridade da mãe.</p>
<p>Além disso, a análise das medianas e dos desvios-padrão mostra que os grupos possuem comportamentos internos diferentes.</p>
<p>O grupo associado ao Ensino Superior apresentou desvio-padrão de aproximadamente <strong>2.05</strong>, enquanto os demais grupos apresentaram dispersões diferentes.</p>
<p>Assim, não é adequado analisar apenas as médias. A mediana e as medidas de dispersão mostram que grupos com centros semelhantes podem apresentar diferentes graus de heterogeneidade.</p>
<p>Também não é possível afirmar, apenas com base nesses resultados, que a escolaridade da mãe determina diretamente a nota do aluno.</p>
</section>
</section>
<section id="faltas-segundo-o-turno-de-estudo-1" class="level2" data-number="17.3">
<h2 data-number="17.3" class="anchored" data-anchor-id="faltas-segundo-o-turno-de-estudo-1"><span class="header-section-number">17.3</span> 6.3 Faltas segundo o Turno de Estudo</h2>
<p>A análise seguinte compara o número de faltas entre os turnos Matutino, Vespertino e Noturno.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>turno_arredondado <span class="ot">&lt;-</span> turno</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>turno_arredondado[, <span class="sc">-</span><span class="dv">1</span>] <span class="ot">&lt;-</span> <span class="fu">round</span>(</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  turno_arredondado[, <span class="sc">-</span><span class="dv">1</span>],</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>  <span class="dv">2</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>turno_arredondado</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>       turno Média Mediana Desvio.Padrão Mínimo Máximo Amplitude AIQ
1   Matutino  8.03       8          2.78      1     17        16   4
2    Noturno  7.95       8          2.65      2     15        13   3
3 Vespertino  8.03       8          2.91      1     19        18   4</code></pre>
</div>
</div>
<section id="comparação-entre-matutino-vespertino-e-noturno-1" class="level3" data-number="17.3.1">
<h3 data-number="17.3.1" class="anchored" data-anchor-id="comparação-entre-matutino-vespertino-e-noturno-1"><span class="header-section-number">17.3.1</span> 6.3.1 Comparação entre Matutino, Vespertino e Noturno</h3>
<p>As médias de faltas foram aproximadamente:</p>
<ul>
<li>Matutino: <strong>8.03</strong>;</li>
<li>Vespertino: <strong>8.03</strong>;</li>
<li>Noturno: <strong>7.95</strong>.</li>
</ul>
<p>O turno Matutino apresentou a maior média de faltas, embora a diferença para o turno Vespertino seja pequena.</p>
<p>As medianas dos três grupos foram próximas, indicando que o número típico de faltas é semelhante entre os turnos.</p>
<p>Em relação à variabilidade, o turno Vespertino apresentou o maior desvio-padrão, aproximadamente <strong>2.91</strong>.</p>
<p>A análise mostra, portanto, que médias semelhantes não significam necessariamente distribuições idênticas.</p>
</section>
</section>
</section>
<section id="representações-gráficas-1" class="level1" data-number="18">
<h1 data-number="18"><span class="header-section-number">18</span> 7 Representações gráficas</h1>
<section id="boxplots-globais-1" class="level2" data-number="18.1">
<h2 data-number="18.1" class="anchored" data-anchor-id="boxplots-globais-1"><span class="header-section-number">18.1</span> 7.1 Boxplots Globais</h2>
<p>Os boxplots permitem visualizar:</p>
<ul>
<li>mediana;</li>
<li>primeiro quartil;</li>
<li>terceiro quartil;</li>
<li>amplitude interquartil;</li>
<li>possíveis valores discrepantes.</li>
</ul>
<section id="boxplot-da-nota-média-1" class="level3" data-number="18.1.1">
<h3 data-number="18.1.1" class="anchored" data-anchor-id="boxplot-da-nota-média-1"><span class="header-section-number">18.1.1</span> 7.1.1 Boxplot da Nota Média</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  dados_alunos<span class="sc">$</span>nota_media,</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">main =</span> <span class="st">"Boxplot da Nota Média"</span>,</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">ylab =</span> <span class="st">"Nota Média"</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p>O boxplot permite observar a posição da mediana e a concentração dos 50% centrais das notas.</p>
<p>A caixa do gráfico representa o intervalo entre Q1 e Q3, enquanto a linha interna representa a mediana.</p>
<p>Pontos eventualmente apresentados fora dos limites dos bigodes representam possíveis valores discrepantes segundo o critério utilizado pelo boxplot.</p>
</section>
<section id="boxplot-das-faltas-1" class="level3" data-number="18.1.2">
<h3 data-number="18.1.2" class="anchored" data-anchor-id="boxplot-das-faltas-1"><span class="header-section-number">18.1.2</span> 7.1.2 Boxplot das Faltas</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  dados_alunos<span class="sc">$</span>faltas,</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">main =</span> <span class="st">"Boxplot do Número de Faltas"</span>,</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">ylab =</span> <span class="st">"Número de Faltas"</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p>O gráfico permite verificar visualmente a concentração das faltas e possíveis observações afastadas do comportamento central.</p>
<p>A interpretação deve ser realizada em conjunto com a mediana, os quartis e a amplitude interquartil calculados anteriormente.</p>
</section>
</section>
<section id="gráficos-comparativos-por-subgrupos-1" class="level2" data-number="18.2">
<h2 data-number="18.2" class="anchored" data-anchor-id="gráficos-comparativos-por-subgrupos-1"><span class="header-section-number">18.2</span> 7.2 Gráficos Comparativos por Subgrupos</h2>
<section id="distribuição-das-notas-por-acesso-à-internet-1" class="level3" data-number="18.2.1">
<h3 data-number="18.2.1" class="anchored" data-anchor-id="distribuição-das-notas-por-acesso-à-internet-1"><span class="header-section-number">18.2.1</span> 7.2.1 Distribuição das Notas por Acesso à Internet</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  nota_media <span class="sc">~</span> acesso_internet,</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> dados_alunos,</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">main =</span> <span class="st">"Distribuição das Notas segundo o Acesso à Internet"</span>,</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">xlab =</span> <span class="st">"Acesso à Internet"</span>,</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">ylab =</span> <span class="st">"Nota Média"</span></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p>O gráfico permite comparar visualmente as medianas, os quartis e a dispersão das notas entre os dois grupos.</p>
<p>Como as medidas centrais são próximas, a análise visual deve ser complementada pelas medidas de dispersão para identificar possíveis diferenças internas.</p>
</section>
<section id="distribuição-das-notas-por-escolaridade-da-mãe-1" class="level3" data-number="18.2.2">
<h3 data-number="18.2.2" class="anchored" data-anchor-id="distribuição-das-notas-por-escolaridade-da-mãe-1"><span class="header-section-number">18.2.2</span> 7.2.2 Distribuição das Notas por Escolaridade da Mãe</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  nota_media <span class="sc">~</span> escolaridade_mae,</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> dados_alunos,</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">main =</span> <span class="st">"Distribuição das Notas segundo a Escolaridade da Mãe"</span>,</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">xlab =</span> <span class="st">"Escolaridade da Mãe"</span>,</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">ylab =</span> <span class="st">"Nota Média"</span></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p>Esse gráfico permite comparar a posição central e a variabilidade das notas nos três grupos.</p>
<p>A análise mostra que não basta verificar qual grupo possui a maior média. É necessário observar também a mediana, a amplitude da distribuição e a dispersão dos valores.</p>
</section>
<section id="distribuição-das-faltas-por-turno-de-estudo-1" class="level3" data-number="18.2.3">
<h3 data-number="18.2.3" class="anchored" data-anchor-id="distribuição-das-faltas-por-turno-de-estudo-1"><span class="header-section-number">18.2.3</span> 7.2.3 Distribuição das Faltas por Turno de Estudo</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  faltas <span class="sc">~</span> turno,</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> dados_alunos,</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">main =</span> <span class="st">"Distribuição das Faltas segundo o Turno de Estudo"</span>,</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">xlab =</span> <span class="st">"Turno"</span>,</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">ylab =</span> <span class="st">"Número de Faltas"</span></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p>O gráfico permite observar que os três turnos possuem medianas próximas, mas podem apresentar diferenças na dispersão e nos valores extremos.</p>
</section>
</section>
<section id="integração-e-interpretação-estatística-dos-gráficos-1" class="level2" data-number="18.3">
<h2 data-number="18.3" class="anchored" data-anchor-id="integração-e-interpretação-estatística-dos-gráficos-1"><span class="header-section-number">18.3</span> 7.3 Integração e interpretação estatística dos gráficos</h2>
<p>Os gráficos confirmam a importância de analisar simultaneamente medidas de posição e dispersão.</p>
<p>A média informa o centro aritmético dos dados, enquanto a mediana indica um valor central menos sensível a extremos.</p>
<p>Os boxplots acrescentam uma representação visual dos quartis, da amplitude interquartil e de possíveis valores discrepantes.</p>
<p>Assim, a combinação entre tabelas e gráficos fornece uma análise mais completa do comportamento dos alunos.</p>
</section>
</section>
<section id="discussão-dos-resultados-1" class="level1" data-number="19">
<h1 data-number="19"><span class="header-section-number">19</span> 8 Discussão dos resultados</h1>
<section id="média-versus-mediana-1" class="level2" data-number="19.1">
<h2 data-number="19.1" class="anchored" data-anchor-id="média-versus-mediana-1"><span class="header-section-number">19.1</span> 8.1 Média versus Mediana</h2>
<p>Considerando a variável Nota Média, a média foi de aproximadamente <strong>6.44</strong>, enquanto a mediana foi de <strong>6.5</strong>.</p>
<p>Como os valores são próximos, ambas as medidas fornecem uma representação semelhante do centro da distribuição.</p>
<p>Entretanto, se fosse necessário escolher apenas uma medida para representar o desempenho típico quando existem possíveis valores extremos, a mediana apresenta uma vantagem por ser menos influenciada por observações muito baixas ou muito altas.</p>
<p>Para representar o desempenho médio global do conjunto, a média é informativa. Para representar o comportamento típico em situações com maior influência de valores extremos, a mediana pode ser mais adequada.</p>
</section>
<section id="o-efeito-da-variabilidade-1" class="level2" data-number="19.2">
<h2 data-number="19.2" class="anchored" data-anchor-id="o-efeito-da-variabilidade-1"><span class="header-section-number">19.2</span> 8.2 O efeito da variabilidade</h2>
<p>Dois grupos podem apresentar médias semelhantes e, ainda assim, possuir comportamentos diferentes.</p>
<p>Por exemplo, um grupo pode apresentar notas concentradas próximas da média, enquanto outro pode possuir alunos com notas muito baixas e muito altas.</p>
<p>Nesse caso, analisar apenas a média poderia levar a uma interpretação incompleta.</p>
<p>As medidas de dispersão, especialmente o desvio-padrão, a amplitude interquartil e o coeficiente de variação, permitem identificar essas diferenças.</p>
<p>Os resultados deste relatório mostram que a variável Faltas apresenta maior variabilidade relativa do que a Nota Média.</p>
</section>
<section id="seleção-das-medidas-estatísticas-mais-adequadas-1" class="level2" data-number="19.3">
<h2 data-number="19.3" class="anchored" data-anchor-id="seleção-das-medidas-estatísticas-mais-adequadas-1"><span class="header-section-number">19.3</span> 8.3 Seleção das medidas estatísticas mais adequadas</h2>
<section id="desempenho-médio-global-1" class="level3" data-number="19.3.1">
<h3 data-number="19.3.1" class="anchored" data-anchor-id="desempenho-médio-global-1"><span class="header-section-number">19.3.1</span> 8.3.1 Desempenho médio global</h3>
<p>Para identificar o desempenho médio global dos alunos, a medida mais informativa é a <strong>média aritmética</strong>, pois utiliza todos os valores observados.</p>
<p>No conjunto analisado, a média da Nota Média foi de aproximadamente <strong>6.44</strong>.</p>
</section>
<section id="desempenho-típico-com-valores-extremos-1" class="level3" data-number="19.3.2">
<h3 data-number="19.3.2" class="anchored" data-anchor-id="desempenho-típico-com-valores-extremos-1"><span class="header-section-number">19.3.2</span> 8.3.2 Desempenho típico com valores extremos</h3>
<p>Quando existem valores extremos, a <strong>mediana</strong> pode ser mais adequada.</p>
<p>Isso ocorre porque a mediana depende da posição central dos dados ordenados e sofre menor influência de observações muito afastadas.</p>
</section>
<section id="dispersão-das-notas-1" class="level3" data-number="19.3.3">
<h3 data-number="19.3.3" class="anchored" data-anchor-id="dispersão-das-notas-1"><span class="header-section-number">19.3.3</span> 8.3.3 Dispersão das notas</h3>
<p>Para avaliar a dispersão das notas, o <strong>desvio-padrão</strong> e a <strong>amplitude interquartil</strong> são medidas particularmente informativas.</p>
<p>O desvio-padrão da Nota Média foi de aproximadamente <strong>1.88</strong>.</p>
</section>
<section id="comparação-da-variabilidade-1" class="level3" data-number="19.3.4">
<h3 data-number="19.3.4" class="anchored" data-anchor-id="comparação-da-variabilidade-1"><span class="header-section-number">19.3.4</span> 8.3.4 Comparação da variabilidade</h3>
<p>Para comparar a variabilidade de variáveis com escalas diferentes, a medida mais adequada é o <strong>coeficiente de variação</strong>.</p>
<p>Neste estudo:</p>
<ul>
<li>CV das Faltas: <strong>34.93%</strong>;</li>
<li>CV da Nota Média: <strong>29.21%</strong>.</li>
</ul>
<p>Portanto, Faltas apresenta maior variabilidade relativa.</p>
</section>
<section id="posição-relativa-de-um-aluno-no-grupo-1" class="level3" data-number="19.3.5">
<h3 data-number="19.3.5" class="anchored" data-anchor-id="posição-relativa-de-um-aluno-no-grupo-1"><span class="header-section-number">19.3.5</span> 8.3.5 Posição relativa de um aluno no grupo</h3>
<p>Para identificar a posição relativa de um aluno em relação aos demais, os <strong>percentis</strong> são especialmente úteis.</p>
<p>Um aluno situado no percentil 90, por exemplo, encontra-se acima de aproximadamente 90% das observações em determinada variável, dependendo do sentido da interpretação.</p>
</section>
</section>
<section id="tabela-síntese-comparativa-1" class="level2" data-number="19.4">
<h2 data-number="19.4" class="anchored" data-anchor-id="tabela-síntese-comparativa-1"><span class="header-section-number">19.4</span> 8.4 Tabela-síntese comparativa</h2>
<p>A tabela seguinte reúne as principais medidas estatísticas das duas variáveis quantitativas.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>tabela_sintese <span class="ot">&lt;-</span> <span class="fu">rbind</span>(</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">Faltas =</span> estat_faltas,</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="st">`</span><span class="at">Nota Média</span><span class="st">`</span> <span class="ot">=</span> estat_notas</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(tabela_sintese, <span class="dv">2</span>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>           Mínimo  Q1 Média Mediana   Q3 Máximo Amplitude AIQ Variância
Faltas        1.0 6.0  8.01     8.0 10.0     19      18.0 4.0      7.83
Nota Média    0.5 5.2  6.44     6.5  7.7     10       9.5 2.5      3.54
           Desvio.Padrão Coeficiente.de.Variação....
Faltas              2.80                       34.93
Nota Média          1.88                       29.21</code></pre>
</div>
</div>
<section id="mínimo-1" class="level3" data-number="19.4.1">
<h3 data-number="19.4.1" class="anchored" data-anchor-id="mínimo-1"><span class="header-section-number">19.4.1</span> 8.4.1 Mínimo</h3>
<p>O menor número de faltas observado foi <strong>1</strong>, enquanto a menor Nota Média foi <strong>0.5</strong>.</p>
</section>
<section id="q1-1" class="level3" data-number="19.4.2">
<h3 data-number="19.4.2" class="anchored" data-anchor-id="q1-1"><span class="header-section-number">19.4.2</span> 8.4.2 Q1</h3>
<p>O primeiro quartil das Faltas foi <strong>6</strong> e o primeiro quartil das Notas foi <strong>5.2</strong>.</p>
</section>
<section id="média-1" class="level3" data-number="19.4.3">
<h3 data-number="19.4.3" class="anchored" data-anchor-id="média-1"><span class="header-section-number">19.4.3</span> 8.4.3 Média</h3>
<p>As médias foram:</p>
<ul>
<li>Faltas: <strong>8.01</strong>;</li>
<li>Nota Média: <strong>6.44</strong>.</li>
</ul>
</section>
<section id="mediana-3" class="level3" data-number="19.4.4">
<h3 data-number="19.4.4" class="anchored" data-anchor-id="mediana-3"><span class="header-section-number">19.4.4</span> 8.4.4 Mediana</h3>
<p>As medianas foram:</p>
<ul>
<li>Faltas: <strong>8</strong>;</li>
<li>Nota Média: <strong>6.5</strong>.</li>
</ul>
</section>
<section id="q3-1" class="level3" data-number="19.4.5">
<h3 data-number="19.4.5" class="anchored" data-anchor-id="q3-1"><span class="header-section-number">19.4.5</span> 8.4.5 Q3</h3>
<p>O terceiro quartil foi:</p>
<ul>
<li>Faltas: <strong>10</strong>;</li>
<li>Nota Média: <strong>7.7</strong>.</li>
</ul>
</section>
<section id="máximo-1" class="level3" data-number="19.4.6">
<h3 data-number="19.4.6" class="anchored" data-anchor-id="máximo-1"><span class="header-section-number">19.4.6</span> 8.4.6 Máximo</h3>
<p>Os valores máximos observados foram:</p>
<ul>
<li>Faltas: <strong>19</strong>;</li>
<li>Nota Média: <strong>10</strong>.</li>
</ul>
</section>
<section id="amplitude-1" class="level3" data-number="19.4.7">
<h3 data-number="19.4.7" class="anchored" data-anchor-id="amplitude-1"><span class="header-section-number">19.4.7</span> 8.4.7 Amplitude</h3>
<p>A amplitude foi:</p>
<ul>
<li>Faltas: <strong>18</strong>;</li>
<li>Nota Média: <strong>9.5</strong>.</li>
</ul>
</section>
<section id="aiq-1" class="level3" data-number="19.4.8">
<h3 data-number="19.4.8" class="anchored" data-anchor-id="aiq-1"><span class="header-section-number">19.4.8</span> 8.4.8 AIQ</h3>
<p>A amplitude interquartil foi:</p>
<ul>
<li>Faltas: <strong>4</strong>;</li>
<li>Nota Média: <strong>2.5</strong>.</li>
</ul>
</section>
<section id="variância-1" class="level3" data-number="19.4.9">
<h3 data-number="19.4.9" class="anchored" data-anchor-id="variância-1"><span class="header-section-number">19.4.9</span> 8.4.9 Variância</h3>
<p>A variância amostral foi:</p>
<ul>
<li>Faltas: <strong>7.83</strong>;</li>
<li>Nota Média: <strong>3.54</strong>.</li>
</ul>
</section>
<section id="desvio-padrão-1" class="level3" data-number="19.4.10">
<h3 data-number="19.4.10" class="anchored" data-anchor-id="desvio-padrão-1"><span class="header-section-number">19.4.10</span> 8.4.10 Desvio-Padrão</h3>
<p>O desvio-padrão foi:</p>
<ul>
<li>Faltas: <strong>2.8</strong>;</li>
<li>Nota Média: <strong>1.88</strong>.</li>
</ul>
</section>
<section id="coeficiente-de-variação-3" class="level3" data-number="19.4.11">
<h3 data-number="19.4.11" class="anchored" data-anchor-id="coeficiente-de-variação-3"><span class="header-section-number">19.4.11</span> 8.4.11 Coeficiente de Variação</h3>
<p>O coeficiente de variação foi:</p>
<ul>
<li>Faltas: <strong>34.93%</strong>;</li>
<li>Nota Média: <strong>29.21%</strong>.</li>
</ul>
<p>A análise da tabela confirma que a variável Faltas apresenta maior variabilidade relativa.</p>
</section>
</section>
</section>
<section id="conclusões-1" class="level1" data-number="20">
<h1 data-number="20"><span class="header-section-number">20</span> 9 Conclusões</h1>
<section id="síntese-dos-achados-sobre-as-variáveis-faltas-e-nota-média-1" class="level2" data-number="20.1">
<h2 data-number="20.1" class="anchored" data-anchor-id="síntese-dos-achados-sobre-as-variáveis-faltas-e-nota-média-1"><span class="header-section-number">20.1</span> 9.1 Síntese dos achados sobre as variáveis Faltas e Nota Média</h2>
<p>A análise mostrou que o número médio de faltas foi de aproximadamente <strong>8.01</strong>, enquanto a mediana foi <strong>8</strong>.</p>
<p>Para a Nota Média, a média foi de aproximadamente <strong>6.44</strong>, e a mediana foi <strong>6.5</strong>.</p>
<p>A proximidade entre média e mediana sugere que, globalmente, essas medidas fornecem informações semelhantes sobre a posição central dos dados.</p>
<p>Entretanto, a análise não deve ser limitada a essas medidas, pois a dispersão mostra diferenças importantes entre as variáveis.</p>
</section>
<section id="identificação-da-variável-de-maior-variabilidade-relativa-1" class="level2" data-number="20.2">
<h2 data-number="20.2" class="anchored" data-anchor-id="identificação-da-variável-de-maior-variabilidade-relativa-1"><span class="header-section-number">20.2</span> 9.2 Identificação da variável de maior variabilidade relativa</h2>
<p>A variável que apresentou maior variabilidade relativa foi <strong>Faltas</strong>.</p>
<p>Seu coeficiente de variação foi de aproximadamente <strong>34.93%</strong>, superior ao coeficiente de variação da Nota Média, que foi de aproximadamente <strong>29.21%</strong>.</p>
<p>Isso indica que o comportamento dos alunos em relação à frequência apresenta maior heterogeneidade proporcionalmente à sua média.</p>
</section>
<section id="resumo-das-diferenças-observadas-entre-os-subgrupos-analisados-1" class="level2" data-number="20.3">
<h2 data-number="20.3" class="anchored" data-anchor-id="resumo-das-diferenças-observadas-entre-os-subgrupos-analisados-1"><span class="header-section-number">20.3</span> 9.3 Resumo das diferenças observadas entre os subgrupos analisados</h2>
<p>A análise dos alunos com e sem acesso à internet mostrou médias e medianas próximas, sem uma diferença descritiva expressiva no desempenho global.</p>
<p>Na comparação por escolaridade da mãe, foram observadas diferenças entre médias, medianas e medidas de dispersão. Entretanto, os resultados não apresentaram uma progressão perfeitamente linear entre os níveis de escolaridade.</p>
<p>Na comparação das faltas por turno, as médias e medianas foram semelhantes, mas houve diferenças na variabilidade dos grupos.</p>
<p>Esses resultados demonstram a importância de analisar simultaneamente medidas de posição e dispersão.</p>
</section>
</section>
<section id="limitações-da-análise-1" class="level1" data-number="21">
<h1 data-number="21"><span class="header-section-number">21</span> 10 Limitações da análise</h1>
<section id="cuidados-e-precauções-na-interpretação-das-diferenças-entre-grupos-1" class="level2" data-number="21.1">
<h2 data-number="21.1" class="anchored" data-anchor-id="cuidados-e-precauções-na-interpretação-das-diferenças-entre-grupos-1"><span class="header-section-number">21.1</span> 10.1 Cuidados e precauções na interpretação das diferenças entre grupos</h2>
<p>As diferenças observadas entre os grupos devem ser interpretadas com cuidado.</p>
<p>Uma diferença entre médias não significa automaticamente que todos os alunos de um grupo apresentem desempenho superior ou inferior aos alunos de outro grupo.</p>
<p>As distribuições podem apresentar sobreposição e diferentes níveis de variabilidade.</p>
</section>
<section id="distinção-entre-descrição-estatística-associação-e-causalidade-1" class="level2" data-number="21.2">
<h2 data-number="21.2" class="anchored" data-anchor-id="distinção-entre-descrição-estatística-associação-e-causalidade-1"><span class="header-section-number">21.2</span> 10.2 Distinção entre descrição estatística, associação e causalidade</h2>
<p>A análise realizada é descritiva.</p>
<p>Ela permite identificar padrões e diferenças observadas no banco de dados, mas não demonstra necessariamente relações de causa e efeito.</p>
<p>Por exemplo, observar diferenças entre alunos com e sem acesso à internet não significa que o acesso à internet seja a causa direta dessas diferenças.</p>
</section>
<section id="impossibilidade-de-inferir-relações-de-causa-e-efeito-sem-controle-de-variáveis-1" class="level2" data-number="21.3">
<h2 data-number="21.3" class="anchored" data-anchor-id="impossibilidade-de-inferir-relações-de-causa-e-efeito-sem-controle-de-variáveis-1"><span class="header-section-number">21.3</span> 10.3 Impossibilidade de inferir relações de causa e efeito sem controle de variáveis</h2>
<p>Diversos fatores podem estar relacionados ao desempenho escolar, como condições socioeconômicas, características da escola, apoio familiar, hábitos de estudo, disponibilidade de recursos e outros fatores não analisados.</p>
<p>Portanto, não é possível afirmar, apenas com base nesta análise descritiva, que a escolaridade da mãe, o acesso à internet ou o turno de estudo sejam responsáveis diretamente pelas diferenças observadas.</p>
<p>Para investigar relações causais seriam necessários estudos adicionais, controle de variáveis e métodos estatísticos apropriados.</p>
</section>
</section>
<section id="código-r-utilizado-1" class="level1" data-number="22">
<h1 data-number="22"><span class="header-section-number">22</span> 11 Código R utilizado</h1>
<section id="importação-e-preparação-dos-dados-1" class="level2" data-number="22.1">
<h2 data-number="22.1" class="anchored" data-anchor-id="importação-e-preparação-dos-dados-1"><span class="header-section-number">22.1</span> 11.1 Importação e preparação dos dados</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>dados_alunos <span class="ot">&lt;-</span> <span class="fu">read.table</span>(</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">file =</span> <span class="st">"dados_alunos.csv"</span>,</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">header =</span> <span class="cn">TRUE</span>,</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">sep =</span> <span class="st">";"</span>,</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">dec =</span> <span class="st">","</span>,</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">stringsAsFactors =</span> <span class="cn">FALSE</span></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>dados_alunos<span class="sc">$</span>nota_media <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(</span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gsub</span>(<span class="st">","</span>, <span class="st">"."</span>, <span class="fu">as.character</span>(dados_alunos<span class="sc">$</span>nota_media))</span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="cálculo-das-medidas-estatísticas-1" class="level2" data-number="22.2">
<h2 data-number="22.2" class="anchored" data-anchor-id="cálculo-das-medidas-estatísticas-1"><span class="header-section-number">22.2</span> 11.2 Cálculo das medidas estatísticas</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(dados_alunos<span class="sc">$</span>faltas)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 8.013</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">median</span>(dados_alunos<span class="sc">$</span>faltas)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 8</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">var</span>(dados_alunos<span class="sc">$</span>faltas)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 7.832664</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(dados_alunos<span class="sc">$</span>faltas)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.79869</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">IQR</span>(dados_alunos<span class="sc">$</span>faltas)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(dados_alunos<span class="sc">$</span>nota_media)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 6.4438</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">median</span>(dados_alunos<span class="sc">$</span>nota_media)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 6.5</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">var</span>(dados_alunos<span class="sc">$</span>nota_media)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3.543665</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(dados_alunos<span class="sc">$</span>nota_media)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.882463</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">IQR</span>(dados_alunos<span class="sc">$</span>nota_media)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.5</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>  dados_alunos<span class="sc">$</span>faltas,</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">probs =</span> <span class="fu">c</span>(<span class="fl">0.10</span>, <span class="fl">0.25</span>, <span class="fl">0.50</span>, <span class="fl">0.75</span>, <span class="fl">0.90</span>)</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>10% 25% 50% 75% 90% 
  5   6   8  10  12 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>  dados_alunos<span class="sc">$</span>nota_media,</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">probs =</span> <span class="fu">c</span>(<span class="fl">0.10</span>, <span class="fl">0.25</span>, <span class="fl">0.50</span>, <span class="fl">0.75</span>, <span class="fl">0.90</span>)</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> 10%  25%  50%  75%  90% 
3.99 5.20 6.50 7.70 9.10 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>cv_faltas <span class="ot">&lt;-</span> <span class="fu">sd</span>(dados_alunos<span class="sc">$</span>faltas) <span class="sc">/</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mean</span>(dados_alunos<span class="sc">$</span>faltas) <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>cv_notas <span class="ot">&lt;-</span> <span class="fu">sd</span>(dados_alunos<span class="sc">$</span>nota_media) <span class="sc">/</span></span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mean</span>(dados_alunos<span class="sc">$</span>nota_media) <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a>cv_faltas</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 34.92686</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>cv_notas</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 29.21355</code></pre>
</div>
</div>
</section>
<section id="análise-dos-subgrupos-1" class="level2" data-number="22.3">
<h2 data-number="22.3" class="anchored" data-anchor-id="análise-dos-subgrupos-1"><span class="header-section-number">22.3</span> 11.3 Análise dos subgrupos</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">aggregate</span>(</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>  nota_media <span class="sc">~</span> acesso_internet,</span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> dados_alunos,</span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">FUN =</span> mean</span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  acesso_internet nota_media
1             Não   6.481818
2             Sim   6.427738</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">aggregate</span>(</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>  nota_media <span class="sc">~</span> escolaridade_mae,</span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> dados_alunos,</span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">FUN =</span> mean</span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  escolaridade_mae nota_media
1      Fundamental   6.328389
2            Médio   6.553813
3         Superior   6.408000</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">aggregate</span>(</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>  faltas <span class="sc">~</span> turno,</span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> dados_alunos,</span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">FUN =</span> mean</span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>       turno   faltas
1   Matutino 8.033259
2    Noturno 7.946078
3 Vespertino 8.026087</code></pre>
</div>
</div>
</section>
<section id="construção-dos-gráficos-1" class="level2" data-number="22.4">
<h2 data-number="22.4" class="anchored" data-anchor-id="construção-dos-gráficos-1"><span class="header-section-number">22.4</span> 11.4 Construção dos gráficos</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(</span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>  dados_alunos<span class="sc">$</span>nota_media,</span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">main =</span> <span class="st">"Boxplot da Nota Média"</span>,</span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">ylab =</span> <span class="st">"Nota Média"</span></span>
<span id="cb54-5"><a href="#cb54-5" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>  dados_alunos<span class="sc">$</span>faltas,</span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">main =</span> <span class="st">"Boxplot do Número de Faltas"</span>,</span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">ylab =</span> <span class="st">"Número de Faltas"</span></span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-16-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(</span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>  nota_media <span class="sc">~</span> acesso_internet,</span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> dados_alunos,</span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">main =</span> <span class="st">"Notas segundo o Acesso à Internet"</span>,</span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">ylab =</span> <span class="st">"Nota Média"</span></span>
<span id="cb56-6"><a href="#cb56-6" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-16-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(</span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>  nota_media <span class="sc">~</span> escolaridade_mae,</span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> dados_alunos,</span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">main =</span> <span class="st">"Notas segundo a Escolaridade da Mãe"</span>,</span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">ylab =</span> <span class="st">"Nota Média"</span></span>
<span id="cb57-6"><a href="#cb57-6" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-16-4.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(</span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>  faltas <span class="sc">~</span> turno,</span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> dados_alunos,</span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">main =</span> <span class="st">"Faltas segundo o Turno"</span>,</span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">ylab =</span> <span class="st">"Número de Faltas"</span></span>
<span id="cb58-6"><a href="#cb58-6" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-16-5.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="referências-bibliográficas-1" class="level1" data-number="23">
<h1 data-number="23"><span class="header-section-number">23</span> 12 Referências bibliográficas</h1>
<p>BENÊVIDE, B. Probabilidade e Estatística – PROFMAT/CA/UFSJ. Universidade Federal de São João del-Rei, 2026. Disponível em: https://bendeivide.github.io/courses/profmat-probest/normal2026.2/. Acesso em: 14 set. 2026.</p>
<p>BENÊVIDE, B. Epaec – Estatística e Probabilidade Aplicada à Educação. Disponível em: https://bendeivide.github.io/books/epaec/. Acesso em: 14 set. 2026.</p>
<p>OPENAI. ChatGPT. Ferramenta de inteligência artificial utilizada como apoio à elaboração, organização e revisão do relatório. Disponível em: https://chatgpt.com/. Acesso em: 14 set. 2026.</p>
<p>https://rei-santos.github.io/Profmatma41/rel02/index.html</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiada");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiada");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>